### ISSUE TITLE
test set

### ISSUE THREAD

**Issue by hazirbas** [ankurhanda/nyuv2-meta-data#1]
Hi Ankur,
Can you please tell me what the difference is between two test set for ground truth? (nyuv2_test_class13.tgz vs. nyuv2_test_class13_eigen.tgz)
Thanks,
Caner

**Comment by ankurhanda** [comment]
I think you only need nyuv2_test_class13.tgz - other should be the same I downloaded form eigen's website. If not that should be the results of his model on the test dataset.

**Comment by hazirbas** [comment]
Hi Ankur,
I just found the label names, however, I believe the list of class names mentioned on the paper [1] is not matching the object indices. For example, index 1 is not 'bed'. Do you have the full list of class index to class label map?

[1] - Indoor Semantic Segmentation using depth information, Couprie et al.
Thanks

**Comment by ankurhanda** [comment]
The mapping is avaible here https://github.com/ankurhanda/SceneNetv1.0/ in the tables. let me know if that helps?

**Comment by magicuter** [comment]
Hi @hazirbas ，
I've just read this paper[1] recently，But I can't see how he turned the NYUv2 dataset into 14 categories,Do you have any information about this?Thank you very much!!!

[1] - Indoor Semantic Segmentation using depth information, Couprie et al.

**Comment by hazirbas** [comment]
Hi @minitaitang,
Once upon a time, I got a file from Mrs. Couprie. So here is the list of remapped indices:

`corresponding_classes_in_Silberman_labeling = [13, 14, 5, 6, 4, 1, 5, 5, 5, 11, 7, 3, 5, 3, 3, 3, 5, 5, 10,...
1, 11, 3, 8, 5, 11, 3, 11, 11, 3, 3, 3, 3, 1, 11, 3, 10, 14, 11, 3, 3, 11, 5, 4, 1, 11, 14, 3, 1,...
14, 3, 5, 1, 11, 3, 3, 11, 11, 3, 12, 3, 3, 6, 3, 8, 3, 3, 3, 3, 3, 3, 13, 3, 3, 3, 3, 3, 3, 8, 11,...
12, 8, 8, 9, 3, 13, 11, 5, 13, 12, 3, 3, 3, 3, 5, 11, 11, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 8, 3, 3, 11,...
3, 11, 3, 3, 3, 3, 3, 11, 3, 3, 3, 8, 3, 1, 3, 3, 3, 3, 3, 7, 3, 3, 3, 3, 3, 5, 3, 3, 3, 1, 3, 3, 7, 3,...
3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3, 3, 2, 5, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 5, 3, 3, 14, 3, 5, 3, 3, 3, 3, 3,...
3, 3, 3, 3, 3, 3, 11, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 9, 7, 3, 3, 3, 3, 13, 3, 3, 3,...
3, 5, 3, 3, 3, 3, 3, 3, 3, 5, 13, 11, 3, 3, 3, 3, 3, 5, 3, 3, 3, 3, 3, 3, 5, 3, 3, 3, 5, 3, 3, 3, 3, 3,...
3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 5, 3, 3, 5, 3, 3, 3, 3,...
3, 3, 3, 3, 3, 3, 3, 3, 5, 3, 3, 3, 11, 3, 3, 3, 3, 3, 11, 3, 3, 3, 3, 3, 3, 1, 3, 3, 3, 3, 3, 3, 3, 3,...
3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 3, 3, 3, 3, 3, 3, 11, 3, 3, 3, 3, 3, 5, 3, 3, 3, 3, 3, 3,...
8, 3, 1, 3, 3, 10, 3, 3, 9, 3, 3, 3, 3, 3, 3, 5, 3, 3, 3, 3, 1, 11, 3, 13, 10, 3, 3, 3, 3, 3, 3, 3, 8,...
3, 3, 3, 3, 3, 3, 3, 3, 11, 3, 8, 3, 3, 3, 3, 3, 3, 5, 3, 3, 3, 8, 8, 3, 3, 1, 3, 3, 3, 3, 3, 3, 3, 3,...
3, 8, 5, 3, 3, 3, 3, 3, 3, 3, 3, 3, 13, 3, 3, 3, 3, 3, 3, 3, 3, 3, 11, 3, 3, 3, 11, 3, 3, 3, 5, 3, 3, 3,...
3, 5, 3, 3, 5, 3, 3, 3, 4, 3, 3, 3, 3, 3, 3, 3, 13, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 3, 3, 5, 3,...
3, 3, 3, 3, 1, 3, 5, 4, 3, 3, 5, 5, 5, 3, 3, 3, 3, 3, 3, 3, 3, 8, 3, 3, 3, 3, 3, 3, 5, 3, 3, 3, 3, 3, 3,...
3, 3, 5, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 5, 3, 3, 3, 8, 3, 3, 3, 3, 3, 3, 5, 3, 5, 3, 3, 3,...
3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 5, 3, 3, 3, 3, 12, 3, 3, 2, 3, 3, 3, 3, 3, 11, 8, 3, 3, 3, 3, 3, 3, 3,...
1, 3, 3, 1, 3, 3, 3, 3, 3, 1, 3, 3, 3, 3, 3, 3, 3, 2, 5, 3, 3, 3, 3, 3, 11, 3, 3, 3, 3, 3, 3, 3, 3, 3,...
3, 3, 3, 3, 3, 3, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 3, 3, 5, 11, 3, 3, 3, 1, 1, 1, 3, 3, 3, 1, 1, 1, 1,...
3, 3, 3, 5, 5, 3, 3, 5, 11, 1, 3, 3, 3, 3, 3, 5, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 5, 3, 3, 3, 3, 3, 3, 3, 3,...
3, 3, 3, 3, 3, 3, 1, 5, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,...
3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 3, 3, 3, 3, 3,...
3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 3, 3, 12, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 8, 3, 3, 3, 3, 3, 3, 3, 3, 3,...
5, 3, 3, 3, 2, 3, 3, 3, 2, 3, 1, 3, 5, 5, 3, 3, 3, 3, 3, 3, 3, 3, 13, 3, 3, 3, 3, 13, 3, 1, 3, 3, 3, 5,...
3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 11, 3, 3, 3, 3, 8, 3, 3, 2, 3, 3, 1, 3, 3, 13, 3, 3, 3,...
7, 3, 8, 3, 1, 13, 3, 3, 3, 8, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 8, 3 ,3 ];`

**Comment by magicuter** [comment]
Hi @hazirbas ,
I find this https://github.com/howard-mahe/nyudv2_class_mapping--classMapping13.mat,but this different from you，which have 13 classes，why？ Thank you !!

**Comment by hazirbas** [comment]
Hi @minitaitang ,
I think they are identical, one of the label is used for unlabeled pixels (ignored label).
