### ISSUE TITLE
Depth / Color intrinsics

### ISSUE THREAD

**Issue by quachconghoang** [ankurhanda/nyuv2-meta-data#2]
I don't find any way to convert depth image to xyz pointcloud.
The resolution is unfamiliar (730 : 530)
Do you have any camera calibration files @ankurhanda

**Comment by ankurhanda** [comment]
This repo is only for RGB-D. You should find everything else in the nyuv2 toolbox.

**Comment by charlesCXK** [comment]
I am very grateful to you for this repo. Because I am new to NYU Depth V2 dataset, and I don't know how to handle the 894 classes in the labels. Thanks for your mapping file !
