### ISSUE TITLE
What does eigen means?

### ISSUE THREAD

**Issue by AtlantixJJ** [ankurhanda/nyuv2-meta-data#6]
What does the eigen named file in test_label means?

**Comment by ankurhanda** [comment]
Table 4 (second last row) https://www.cv-foundation.org/openaccess/content_cvpr_2016/papers/Handa_Understanding_Real_World_CVPR_2016_paper.pdf

**Comment by ankurhanda** [comment]
also this https://cs.nyu.edu/~deigen/dnl/
