### ISSUE TITLE
Confused about the label in mat file

### ISSUE THREAD

**Issue by AtlantixJJ** [ankurhanda/nyuv2-meta-data#7]
I open the nyu_depth_v2_labeled.mat file and access its label attribute. When I do a max over the label file, I get 894. How should I extract semantic label from it? Shouldn't label be indexing 0~12 classes?
My final goal is to get the instance segmentation mask, bounding box along with its class label. Can I ask you to recommend any ways to do it? Thank you!

**Comment by ankurhanda** [comment]
The repo has everything, did you check that? 

![nyu_v2](https://user-images.githubusercontent.com/686480/67249307-1c259f00-f41c-11e9-82d0-5fd1ba2df2e9.png)

**Comment by AtlantixJJ** [comment]
I think these two dir only contain semantic label. Where is instance label?
