### ISSUE TITLE
nyuv2 dataset "namesToIds"

### ISSUE THREAD

**Issue by ankan2709** [ankurhanda/nyuv2-meta-data#9]
How do we get the list of all the classes along with the lDs ? I checked the original .mat (2.8 GB) file but was not able to access it.

**Comment by ankurhanda** [comment]
<img width="915" alt="Screenshot 2022-06-29 at 05 04 11" src="https://user-images.githubusercontent.com/686480/176431988-5bdcf73c-51f4-4ee5-8588-df1aaa77d2e6.png">
 
 They are in the github repo.
